### ISSUE TITLE
partial render not working on CI

### ISSUE THREAD

**Issue by andrewpbray** [stat20/course-materials#615]
@paciorek @ryanlovett There's a bug here that I've been having trouble figuring out if you want to take a crack.

I've switched the Stat 20 repo over to using the new partial rendering approach found in [quarto-class-website](https://github.com/qmd-lab/quarto-class-website/tree/master). It works fine when I run it locally: I run

```bash
quarto run partial-render.ts
```

And after about 10-20 minutes, it finishes the partial render and puts the site in `_partial-site`. I can then successfully publish it using

```bash
quarto publish netlify --profile partial-site --no-render --id 1188ba29-f00d-4f5a-ac6f-75c715522c69
```

Those same two steps approach in the github workflow found here:

<https://github.com/stat20/stat20/blob/main/.github/workflows/publish-stat20.yml>

For whatever reason, though, it seems like its getting hung up on the document rendering stage. It's frustrating though: because I'm invoking `quarto render` at the end of `partial-render.ts`, it is run as a child process and the console log is kept in a buffer, so I can't tell which doc its hanging up on (fwiw, [I've asked the Quarto devs about that](https://github.com/quarto-dev/quarto-cli/discussions/8467)).

### Debug attempt 1
*Test `partial-render.ts` in CI on simpler repo*

I set up a [roughly analogous workflow](https://github.com/qmd-lab/quarto-class-website/blob/master/.github/workflows/render-via-script.yml) on the `quarto-class-website` (minus the publish step), and it seems to [work just fine](https://github.com/qmd-lab/quarto-class-website/actions/runs/7687667918). That makes me think there's some weird thing in one of the docs that CI is having a hard time with; an http request or something.

### Debug attempt 2
*Pull out `quarto render` step from `partial-render.ts`*

In order to see which doc was causing the problem, [I modified](https://github.com/stat20/stat20/commit/1a947593cb1aeda0fb173b89059727ca496bfd3b) `partial-render.ts` so that it doesn't call `quarto render` as the last step and instead we call that command as part of the bash script. So the workflow changes to look like this:

```bash
# render partial site
quarto run partial-render.ts

# render for real
quarto render --profile partial-site

# publish rendered site to stat20.org
quarto publish netlify --profile partial-site --no-render --id 1188ba29-f00d-4f5a-ac6f-75c715522c69
```
            
Interestingly, [this workflow goes through no problem](https://github.com/stat20/stat20/actions/runs/7688256719/job/20949261475). So there's some problem with rendering one of those docs as a child process.

All I could think of was to be sure that the script has appropriate read/write permissions, so I tried changing the original action to `quarto run partial-render.ts --allow-read --allow-write` but it still hung up. It's unclear to me if that was the problem and whether passing Deno options like this through `quarto run` is actually taking effect.

Any other ideas come to mind? Let me know if you need permissions to test CI stuff on this repo (you can always remove the publish step so remove worry about messing up stat20.org).

PS: the reason why the fix in attempt 2 doesn't work generally is I'd like to have just a single script and single command that will work the same locally as in CI: `quarto run partial-render.ts`.

**Comment by paciorek** [comment]
Am I understanding correctly that the failure happens only under CI and only with the stat20 content?

**Comment by andrewpbray** [comment]
Yep, correct. I think the most fundamental issue is the buffering of the `quarto render` command's helpful console logs: without them, I can't tell which doc is fouling up the CI build. I haven't been able to figure out how to return those in real time to the console when the `quarto render` command is run as a shell command within the ts script.

**Comment by paciorek** [comment]
@andrewpbray would it help to  loop over all the individual files and render them one by one in the ts file? OTOH that would only identify which file is the culprit and not why. 

Or, I don't understand how the `asynch` and `await` work, but perhaps one could monkey with `stdout` and `stderr` args to `run` in hope that it would show up in the GHA output.

**Comment by paciorek** [comment]
I wonder if [this example](https://examples.deno.land/subprocesses-output) would be useful in terms of being able to start a process but every so often look at stdout/stderr while it is running.

**Comment by andrewpbray** [comment]
I'll take a crack at this again tomorrow morning. @ryanlovett do you have a sense of what Carlos means here?

[https://github.com/quarto-dev/quarto-cli/discussions/8467#discussioncomment-8312237](https://github.com/quarto-dev/quarto-cli/discussions/8467#discussioncomment-8312237)

Does he mean just doing some modification of `quarto render` in the bash shell? I have no experience handling stdin/out/err in a shell, but I had search around if that seems like the right route.

**Comment by andrewpbray** [comment]
@paciorek Monkeying around with the run args is exactly what I was trying, with no success. I have only a hazy sense of async and await (makes me want to learn more cause its an interesting idea) but I don't think that's the issue here.

**Comment by andrewpbray** [comment]
Thanks both for having a look.

**Comment by ryanlovett** [comment]
@andrewpbray Regarding:
> If you run quarto from a shell and redirect the output to stderr, do you still get this behavror?

He means that you'd take your quarto command and put it in a bash script, e.g.

```
$ cat myscript.sh
#!/bin/bash
quarto arg1 arg2 1>&2

$ 
```

And then call `/path/to/myscript.sh` instead of your quarto invocation, does the same thing happen? In this example code, bash is sending stdout (1) to stderr (2). If this works, it would suggest that either bash is altering the buffering behavior or that stderr is not being buffered.

There are Linux commands like `stdbuf` or `unbuffer` that can be inserted into the script to change buffering behavior if necessary.

**Comment by andrewpbray** [comment]
Well: I upgraded from Quarto 1.3 to 1.4 this morning to work on something else and when I came back to work on this... seems like it no longer buffers!

Would one of you mind trying testing to see if this resolves it on your machine too? I'm on macos monterey fwiw.

**Comment by paciorek** [comment]
I may not be following this well enough to weigh in, but if the problem was on CI, then how is your local Quarto version relevant?

**Comment by andrewpbray** [comment]
It doesn't solve the ultimate problem of problems rendering in CI, but it seems to solve the fact that we can't debug CI because of the buffering.

**Comment by andrewpbray** [comment]
(I have on deck a PR to upgrade quarto in the Stat 20 image. If indeed 1.4 solves the buffering issue, this should make it possible to do more informed troubleshooting of the CI renders)

**Comment by andrewpbray** [comment]
Now that I can see the console logs on the CI renders, I was able to find the offending document: a pdf throwing a classic "not in out par mode" latex error. I've fixed those so now all of the CI work 🎉

Not the most gratifying resolution to this question, but an effective one nonetheless.
